<?php

namespace Proxies\__CG__\Ecommerce\EcommerceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \Ecommerce\EcommerceBundle\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'images', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'boutique', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'categorie', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'designationP', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'prix', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'inCatalogue', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'inPromotion', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'qtStock', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'tauxRemise'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'images', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'boutique', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'categorie', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'designationP', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'prix', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'inCatalogue', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'inPromotion', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'qtStock', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Produit' . "\0" . 'tauxRemise'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignationP($designationP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignationP', [$designationP]);

        return parent::setDesignationP($designationP);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignationP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignationP', []);

        return parent::getDesignationP();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setInCatalogue($inCatalogue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInCatalogue', [$inCatalogue]);

        return parent::setInCatalogue($inCatalogue);
    }

    /**
     * {@inheritDoc}
     */
    public function getInCatalogue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInCatalogue', []);

        return parent::getInCatalogue();
    }

    /**
     * {@inheritDoc}
     */
    public function setInPromotion($inPromotion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInPromotion', [$inPromotion]);

        return parent::setInPromotion($inPromotion);
    }

    /**
     * {@inheritDoc}
     */
    public function getInPromotion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInPromotion', []);

        return parent::getInPromotion();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtStock($qtStock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtStock', [$qtStock]);

        return parent::setQtStock($qtStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtStock', []);

        return parent::getQtStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxRemise($tauxRemise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxRemise', [$tauxRemise]);

        return parent::setTauxRemise($tauxRemise);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxRemise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxRemise', []);

        return parent::getTauxRemise();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoutique(\Ecommerce\EcommerceBundle\Entity\Boutique $boutique = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoutique', [$boutique]);

        return parent::setBoutique($boutique);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoutique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoutique', []);

        return parent::getBoutique();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\Ecommerce\EcommerceBundle\Entity\Images $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', [$image]);

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\Ecommerce\EcommerceBundle\Entity\Images $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', [$image]);

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\Ecommerce\EcommerceBundle\Entity\Categorie $categorie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneCommande', []);

        return parent::getLigneCommande();
    }

}
