parameters:
#    ecommerce.example.class: Ecommerce\EcommerceBundle\Example

services:
#    ecommerce.example:
#        class: %ecommerce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
 redirectionListener:
      class: Ecommerce\EcommerceBundle\Listener\RedirectionListener
      arguments: [@service_container,@session]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
