<?php

namespace Ecommerce\EcommerceBundle\Repositories;

/**
 * BoutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoutiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
