<?php

namespace Ecommerce\EcommerceBundle\Repositories;

/**
 * Ligne_CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ligne_CommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
